"use client";
import { Database, FileJson2, LoaderCircle, PanelRightOpen, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocale } from "@/features/i18n/locale-provider";
import styles from "./judge-drawer.module.css";

type Evidence = { id: string; requestCode?: string; event_type: string; provider_url?: string; navigation_url?: string; tool_name?: string; input_payload?: unknown; output_payload?: unknown; duration_ms?: number; status: string; execution_status?: string; persisted_entity_type?: string; persisted_entity_id?: string; created_at: string };
export function JudgeDrawer() {
  const { t } = useLocale(); const [open,setOpen]=useState(false); const [events,setEvents]=useState<Evidence[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const drawer=useRef<HTMLElement>(null); const trigger=useRef<HTMLButtonElement>(null); const close=useRef<HTMLButtonElement>(null);
  useEffect(()=>{ if(!open)return; setLoading(true); setError(""); void fetch("/api/judge/evidence").then(async response=>{ if(!response.ok)throw new Error(); const data=await response.json() as {events:Evidence[]}; setEvents(data.events); }).catch(()=>setError(t("No fue posible cargar la evidencia.","Could not load evidence."))).finally(()=>setLoading(false)); },[open,t]);
  useEffect(()=>{ if(!open)return; const previous=document.body.style.overflow; document.body.style.overflow="hidden"; close.current?.focus(); const key=(event:KeyboardEvent)=>{ if(event.key==="Escape")setOpen(false); if(event.key!=="Tab")return; const items=drawer.current?.querySelectorAll<HTMLElement>('button,a[href],summary,[tabindex]:not([tabindex="-1"])'); if(!items?.length)return; const first=items[0],last=items[items.length-1]; if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}; document.addEventListener("keydown",key); return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",key);trigger.current?.focus();};},[open]);
  return <><button ref={trigger} className={styles.trigger} type="button" aria-haspopup="dialog" aria-expanded={open} title="Judge Drawer" onClick={()=>setOpen(true)}><PanelRightOpen size={18}/><span>Judge</span></button>{open?<><button className={styles.backdrop} type="button" aria-label={t("Cerrar evidencia","Close evidence")} onClick={()=>setOpen(false)}/><aside ref={drawer} className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="judge-title"><header><div><span>Golden Flow</span><h2 id="judge-title">Judge Drawer</h2></div><button ref={close} type="button" aria-label={t("Cerrar","Close")} onClick={()=>setOpen(false)}><X size={19}/></button></header><div className={styles.note}><Database size={17}/><p>{t("Evidencia persistida visible para la organización activa. Los fixtures y reset permanecen aislados de esta interfaz.","Persisted evidence visible to the active organization. Fixtures and reset remain isolated from this interface.")}</p></div>{loading?<div className={styles.empty}><LoaderCircle className={styles.spin}/>{t("Cargando evidencia","Loading evidence")}</div>:error?<div className={styles.empty} role="alert">{error}</div>:events.length?<div className={styles.events}>{events.map(event=><details key={event.id}><summary><FileJson2 size={15}/><span><strong>{event.tool_name??event.event_type}</strong><small>{event.requestCode??event.status} · {event.duration_ms==null?"—":`${event.duration_ms} ms`}</small></span></summary><dl><dt>provider URL</dt><dd>{event.provider_url??"—"}</dd><dt>navigation URL</dt><dd>{event.navigation_url??"—"}</dd><dt>status</dt><dd>{event.execution_status??event.status}</dd><dt>{t("Entidad persistida","Persisted entity")}</dt><dd>{event.persisted_entity_type&&event.persisted_entity_id?`${event.persisted_entity_type}: ${event.persisted_entity_id}`:"—"}</dd></dl><h3>input</h3><pre>{JSON.stringify(event.input_payload,null,2)??"null"}</pre><h3>output</h3><pre>{JSON.stringify(event.output_payload,null,2)??"null"}</pre></details>)}</div>:<div className={styles.empty}>{t("No hay eventos de orquestación persistidos.","No persisted orchestration events.")}</div>}</aside></>:null}</>;
}
