import {
  CargoCategory,
  Carrier,
  CarrierMetrics,
  CarrierService,
  FreightRequest,
  Organization,
  OrganizationPreferences,
  User,
  Vehicle,
} from "../freight/types";

export const MOCK_CATEGORIES: CargoCategory[] = [
  { id: "cat-gen", code: "GENERAL", name: "Carga General", description: "Mercancía paletizada, repuestos mineros y bultos estándar", active: true },
  { id: "cat-food", code: "FOOD", name: "Alimentos y Perecibles", description: "Alimentos procesados y perecibles con o sin cadena de frío", active: true },
  { id: "cat-pharma", code: "PHARMA", name: "Farmacéuticos", description: "Medicamentos y suministros biológicos con control térmico", active: true },
  { id: "cat-chem", code: "CHEMICAL", name: "Químicos / HAZMAT", description: "Compuestos industriales y sustancias químicas controladas", active: true },
  { id: "cat-mach", code: "MACHINERY", name: "Maquinaria y Minería", description: "Equipos mineros, bombas hidráulicas y repuestos pesados", active: true },
  { id: "cat-const", code: "CONSTRUCTION", name: "Construcción", description: "Materiales y herramientas de obra", active: true },
  { id: "cat-agri", code: "AGRICULTURAL", name: "Agroexportación", description: "Cosechas a granel, granos y productos agrícolas", active: true },
  { id: "cat-liq", code: "LIQUID", name: "Líquidos a Granel", description: "Líquidos industriales en camiones cisterna", active: true },
];

export const MOCK_ORGANIZATION: Organization = {
  id: "org-acme",
  name: "ACME Mining Corp",
  code: "ACME",
  status: "ACTIVE",
  default_currency: "USD",
  created_at: "2026-01-15T00:00:00Z",
};

export const MOCK_USER: User = {
  id: "usr-carlos",
  organization_id: "org-acme",
  name: "Carlos Mendoza",
  email: "carlos.mendoza@acmemining.pe",
  role: "LOGISTICS_MANAGER",
  status: "ACTIVE",
};

export const MOCK_PREFERENCES: OrganizationPreferences = {
  id: "pref-acme",
  organization_id: "org-acme",
  default_optimization_strategy: "BALANCED",
  max_pickup_wait_hours: 2,
  preferred_carrier_id: null,
  preferred_vehicle_brand: null,
  budget_default: 2000,
  allow_auto_booking: true,
  confidence_threshold: 85,
  usual_budget_min: 1600,
  usual_budget_max: 2000,
  frequent_routes: ["Lima, Peru -> Santiago, Chile", "Lima, Peru -> Arequipa, Peru"],
};

export const MOCK_CARRIERS: Carrier[] = [
  {
    id: "car-andes",
    name: "Andes Freight",
    code: "ANDES",
    provider_type: "CARRIER",
    status: "ACTIVE",
    description: "Transportista regional líder en el corredor internacional Lima-Santiago con 96% de puntualidad y gestión MIC/DTA.",
    fleet_size: 28,
    created_at: "2025-06-01T00:00:00Z",
  },
  {
    id: "car-pacific",
    name: "Pacific Cargo",
    code: "PACIFIC",
    provider_type: "SMALL_FLEET",
    status: "ACTIVE",
    description: "Flota de costo competitivo para fletes directos en carretera sin inspección prioritaria en frontera.",
    fleet_size: 12,
    created_at: "2025-08-10T00:00:00Z",
  },
  {
    id: "car-inca",
    name: "Inca Logistics",
    code: "INCA",
    provider_type: "ENTERPRISE_CARRIER",
    status: "ACTIVE",
    description: "Red corporativa premium con unidades Volvo FH de alta capacidad y máximo estándar de SLA internacional.",
    fleet_size: 65,
    created_at: "2025-01-20T00:00:00Z",
  },
];

export const MOCK_SERVICES: CarrierService[] = [
  {
    id: "srv-andes-01",
    carrier_id: "car-andes",
    transport_mode: "ROAD",
    service_type: "FTL",
    origin_country: "PE",
    origin_region: "Lima",
    destination_country: "CL",
    destination_region: "Santiago",
    max_capacity_kg: 22000,
    max_volume_m3: 65,
    supports_refrigerated: true,
    temperature_min_c: -18,
    temperature_max_c: 25,
    supports_hazardous: false,
    supports_fragile: true,
    supports_oversized: false,
    active: true,
    supported_cargo_categories: ["GENERAL", "FOOD", "MACHINERY", "CONSTRUCTION", "AGRICULTURAL"],
  },
  {
    id: "srv-pacific-01",
    carrier_id: "car-pacific",
    transport_mode: "ROAD",
    service_type: "FTL",
    origin_country: "PE",
    origin_region: "Lima",
    destination_country: "CL",
    destination_region: "Santiago",
    max_capacity_kg: 18000,
    max_volume_m3: 50,
    supports_refrigerated: false,
    supports_hazardous: false,
    supports_fragile: false,
    supports_oversized: false,
    active: true,
    supported_cargo_categories: ["GENERAL", "CONSTRUCTION", "AGRICULTURAL"],
  },
  {
    id: "srv-inca-01",
    carrier_id: "car-inca",
    transport_mode: "ROAD",
    service_type: "FTL",
    origin_country: "PE",
    origin_region: "Lima",
    destination_country: "CL",
    destination_region: "Santiago",
    max_capacity_kg: 28000,
    max_volume_m3: 85,
    supports_refrigerated: true,
    temperature_min_c: -25,
    temperature_max_c: 30,
    supports_hazardous: true,
    supports_fragile: true,
    supports_oversized: true,
    active: true,
    supported_cargo_categories: ["GENERAL", "FOOD", "PHARMA", "CHEMICAL", "MACHINERY", "CONSTRUCTION", "AGRICULTURAL", "LIQUID"],
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "veh-and-01",
    carrier_id: "car-andes",
    code: "AND-TRK-101",
    brand: "Scania",
    vehicle_type: "Heavy Semi-Trailer R450 18t",
    capacity_kg: 18000,
    volume_m3: 55,
    supports_refrigerated: true,
    supports_hazardous: false,
    supports_oversized: false,
    location: "Terminal Lima Callao, PE",
    status: "AVAILABLE",
  },
  {
    id: "veh-and-02",
    carrier_id: "car-andes",
    code: "AND-TRK-102",
    brand: "Scania",
    vehicle_type: "Box Truck 12t",
    capacity_kg: 12000,
    volume_m3: 40,
    supports_refrigerated: false,
    supports_hazardous: false,
    supports_oversized: false,
    location: "Terminal Callao, PE",
    status: "AVAILABLE",
  },
  {
    id: "veh-pac-01",
    carrier_id: "car-pacific",
    code: "PAC-TRK-301",
    brand: "Freightliner",
    vehicle_type: "Flatbed Truck 15t",
    capacity_kg: 15000,
    volume_m3: 45,
    supports_refrigerated: false,
    supports_hazardous: false,
    supports_oversized: false,
    location: "Terminal Lima Sur, PE",
    status: "AVAILABLE",
  },
  {
    id: "veh-inc-01",
    carrier_id: "car-inca",
    code: "INC-TRK-901",
    brand: "Volvo",
    vehicle_type: "Volvo FH Globetrotter 24t",
    capacity_kg: 24000,
    volume_m3: 75,
    supports_refrigerated: true,
    supports_hazardous: true,
    supports_oversized: true,
    location: "Terminal Ate Central, PE",
    status: "AVAILABLE",
  },
];

export const MOCK_METRICS: Record<string, CarrierMetrics> = {
  "car-pacific": {
    id: "met-pac",
    carrier_id: "car-pacific",
    transport_mode: "ROAD",
    origin_country: "PE",
    origin_city: "Lima",
    destination_country: "CL",
    destination_city: "Santiago",
    completed_freight_requests: 18,
    successful_freight_requests: 15,
    success_rate: 0.86,
    avg_cost: 1590,
    avg_delay_hours: 3.4,
    cancellation_rate: 0.08,
    available_units_count: 1,
    route_jobs_count: 13,
    client_history_trips: 2,
    client_history_ontime: 1,
    updated_at: "2026-08-27T12:00:00Z",
  },
  "car-andes": {
    id: "met-and",
    carrier_id: "car-andes",
    transport_mode: "ROAD",
    origin_country: "PE",
    origin_city: "Lima",
    destination_country: "CL",
    destination_city: "Santiago",
    completed_freight_requests: 64,
    successful_freight_requests: 61,
    success_rate: 0.96,
    avg_cost: 1760,
    avg_delay_hours: 1.2,
    cancellation_rate: 0.02,
    available_units_count: 4,
    route_jobs_count: 42,
    client_history_trips: 9,
    client_history_ontime: 8,
    updated_at: "2026-08-27T12:00:00Z",
  },
  "car-inca": {
    id: "met-inc",
    carrier_id: "car-inca",
    transport_mode: "ROAD",
    origin_country: "PE",
    origin_city: "Lima",
    destination_country: "CL",
    destination_city: "Santiago",
    completed_freight_requests: 92,
    successful_freight_requests: 90,
    success_rate: 0.98,
    avg_cost: 1920,
    avg_delay_hours: 0.8,
    cancellation_rate: 0.01,
    available_units_count: 3,
    route_jobs_count: 35,
    client_history_trips: 4,
    client_history_ontime: 4,
    updated_at: "2026-08-27T12:00:00Z",
  },
};

export const INITIAL_FREIGHT_REQUESTS: FreightRequest[] = [
  {
    id: "fr-1042",
    code: "FR-1042",
    organization_id: "org-acme",
    requested_by_user_id: "usr-carlos",
    cargo_category_id: "cat-gen",
    origin_country: "Peru",
    origin_city: "Lima",
    destination_country: "Chile",
    destination_city: "Santiago",
    cargo_weight_kg: 8000,
    cargo_volume_m3: 18,
    package_count: 12,
    service_type: "FTL",
    transport_mode: "ROAD",
    requires_refrigeration: false,
    is_hazardous: false,
    is_fragile: false,
    is_oversized: false,
    is_high_value: false,
    is_stackable: true,
    special_instructions: "Repuestos para perforadora minera en cajas de madera. Requiere montacargas estándar y trámite MIC/DTA en paso fronterizo Santa Rosa/Chacalluta.",
    required_pickup: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    delivery_deadline: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    max_pickup_wait_hours: 2,
    budget_max: 2000,
    optimization_strategy: "BALANCED",
    status: "PENDING",
    created_at: new Date().toISOString(),
  },
  {
    id: "fr-1043",
    code: "FR-1043",
    organization_id: "org-acme",
    requested_by_user_id: "usr-carlos",
    cargo_category_id: "cat-mach",
    origin_country: "Peru",
    origin_city: "Lima",
    destination_country: "Chile",
    destination_city: "Santiago",
    cargo_weight_kg: 8000,
    cargo_volume_m3: 20,
    package_count: 4,
    service_type: "FTL",
    transport_mode: "ROAD",
    requires_refrigeration: false,
    is_hazardous: false,
    is_fragile: false,
    is_oversized: false,
    special_instructions: "Bomba hidráulica de alta precisión. Preferencia blanda por unidad Volvo FH.",
    required_pickup: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    delivery_deadline: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    max_pickup_wait_hours: 2,
    budget_max: 2000,
    optimization_strategy: "BALANCED",
    preferred_vehicle_brand: "Volvo",
    status: "PENDING",
    created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
  {
    id: "fr-1044",
    code: "FR-1044",
    organization_id: "org-acme",
    requested_by_user_id: "usr-carlos",
    cargo_category_id: "cat-gen",
    origin_country: "Peru",
    origin_city: "Lima",
    destination_country: "Chile",
    destination_city: "Santiago",
    cargo_weight_kg: 10000,
    cargo_volume_m3: 25,
    package_count: 8,
    service_type: "FTL",
    transport_mode: "ROAD",
    requires_refrigeration: false,
    is_hazardous: false,
    is_fragile: true,
    is_oversized: false,
    special_instructions: "Fajas transportadoras de reposición urgente. Escenario de contingencia / avería mecánica en ruta.",
    required_pickup: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    delivery_deadline: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
    budget_max: 2100,
    optimization_strategy: "BALANCED",
    status: "IN_TRANSIT",
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];
