"""Explicit strict identities excluded from the unchanged baseline selection."""
from fk_inventory import hac41_records, identity

STRICT_FK_IDENTITIES = frozenset({
    ('private.v2_catalog_grants', 'v2_catalog_grants_auth_user_id_fkey'),
    ('private.v2_catalog_grants', 'v2_catalog_grants_carrier_id_fkey'),
    ('private.v2_catalog_receipts', 'v2_catalog_receipts_member_id_fkey'),
    ('private.v2_catalog_receipts', 'v2_catalog_receipts_organization_id_fkey'),
    ('private.v2_facility_command_receipts', 'v2_facility_command_receipts_facility_id_organization_id_fkey'),
    ('private.v2_facility_command_receipts', 'v2_facility_command_receipts_member_id_fkey'),
    ('private.v2_facility_command_receipts', 'v2_facility_command_receipts_organization_id_fkey'),
    ('private.v2_organization_command_receipts', 'v2_organization_command_receipts_member_id_fkey'),
    ('private.v2_organization_command_receipts', 'v2_organization_command_receipts_organization_id_fkey'),
    ('private.v2_request_command_receipts', 'v2_request_command_receipts_member_id_fkey'),
    ('private.v2_request_command_receipts', 'v2_request_command_receipts_organization_id_fkey'),
    ('private.v2_request_command_receipts', 'v2_request_command_receipts_request_id_fkey'),
    ('private.v2_workflow_receipts', 'v2_workflow_receipts_member_id_fkey'),
    ('private.v2_workflow_receipts', 'v2_workflow_receipts_organization_id_fkey'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_cargo_category_id_fkey'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_carrier_id_fkey'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_carrier_service_id_fkey'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_definition_id_fkey'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_fleet_service'),
    ('public.asset_cargo_capabilities', 'asset_cargo_capabilities_transport_asset_id_fkey'),
    ('public.asset_cargo_capabilities', 'fleet_definition_asset_scope'),
    ('public.capacity_consolidations', 'capacity_consolidations_calendar_id_fkey'),
    ('public.capacity_consolidations', 'capacity_consolidations_carrier_id_fkey'),
    ('public.capacity_consolidations', 'capacity_consolidations_freight_request_id_fkey'),
    ('public.capacity_consolidations', 'capacity_consolidations_organization_id_fkey'),
    ('public.capacity_consolidations', 'capacity_consolidations_route_id_fkey'),
    ('public.capacity_consolidations', 'consolidation_service_fk'),
    ('public.execution_events', 'execution_event_execution_fk'),
    ('public.execution_events', 'execution_events_carrier_id_fkey'),
    ('public.execution_events', 'execution_events_consolidation_id_fkey'),
    ('public.execution_events', 'execution_events_freight_request_id_fkey'),
    ('public.execution_events', 'execution_events_organization_id_fkey'),
    ('public.incident_route_conditions', 'incident_route_conditions_condition_id_fkey'),
    ('public.incident_route_conditions', 'incident_route_conditions_incident_id_fkey'),
    ('public.plan_leg_assignments', 'plan_leg_assignments_fulfilment_partner_id_fkey'),
    ('public.plan_resource_bindings', 'plan_leg_assignments_carrier_service_id_fkey'),
    ('public.plan_resource_bindings', 'plan_leg_assignments_lane_id_fkey'),
    ('public.plan_resource_bindings', 'plan_leg_assignments_plan_id_fkey'),
    ('public.plan_resource_bindings', 'plan_leg_assignments_resource_id_plan_id_fkey'),
    ('public.plan_resource_bindings', 'plan_leg_assignments_route_leg_id_fkey'),
    ('public.plan_resource_bindings', 'resource_binding_leg_fk'),
    ('public.v2_rankings', 'v2_rankings_carrier_id_fkey'),
    ('public.v2_rankings', 'v2_rankings_freight_request_id_fkey'),
    ('public.v2_rankings', 'v2_rankings_organization_id_fkey'),
    ('public.v2_rankings', 'v2_rankings_policy_id_fkey'),
})
STRICT_FK_IDENTITIES = STRICT_FK_IDENTITIES | frozenset(identity(row) for row in hac41_records())
