-- HAC-40 CP-1: mandatory values, domain revision and auditable planner snapshots.
-- No synthetic records. Auxiliary carrying capacity is zero in the API; legacy
-- storage retains NULL for ESCORT so it cannot become a capacity source.

create or replace function private.fleet_record(p_kind text,p_id uuid) returns jsonb language plpgsql set search_path='' as $$
declare result jsonb;begin case p_kind
when 'capability-definitions' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'categoryId',r.cargo_category_id,'requirements',r.requirements,'maxWeightKg',r.max_weight_kg,'temperatureRange',r.temperature_range,'certifications',r.certifications,'evidence',r.evidence,'verifiedAt',r.verified_at,'validUntil',r.valid_until,'active',r.active)) into result from public.cargo_capability_definitions r where r.id=p_id;
when 'assets' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'code',r.code,'mode',r.mode,'equipmentType',r.equipment_code,'role',case when r.asset_role='CARRIER' then 'LOAD_BEARING' else 'AUXILIARY' end,'usefulCapacityKg',case when r.asset_role='ESCORT' then 0 else r.max_weight_kg end,'usableVolumeM3',r.max_volume_m3,'operatingStatus',r.operating_status,'homeDepotId',r.home_depot_id,'provenance',r.fulfilment_source,'partnerId',r.fulfilment_partner_id,'evidence',r.evidence,'roadVehicle',case when r.mode='ROAD' then jsonb_build_object('plate',r.plate,'registrationCode',r.registration_code,'registeredAt',r.registered_at,'brand',r.brand,'model',r.model,'variant',r.variant,'bodyType',r.body_type,'usableDimensions',r.usable_dimensions,'grossWeightLimitKg',r.gross_weight_limit_kg,'odometerKm',r.odometer_km,'conditionReason',r.condition_reason,'axleConfig',r.axle_config) else null end)) into result from public.transport_assets r where r.id=p_id;
when 'capacity-pools' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'code',r.code,'mode',r.mode,'equipmentType',r.equipment_code,'serviceWindow',case when r.starts_at is null then null else jsonb_build_object('startsAt',r.starts_at,'endsAt',r.ends_at) end,'declaredCapacity',jsonb_build_object('weightKg',r.max_weight_kg,'volumeM3',r.max_volume_m3),'provenance',r.fulfilment_source,'partnerId',r.fulfilment_partner_id,'evidence',r.evidence,'supportedCargoCategoryIds',r.supported_cargo_category_ids,'active',r.active)) into result from public.capacity_pools r where r.id=p_id;
when 'calendars' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'assetId',r.transport_asset_id,'capacityPoolId',r.capacity_pool_id,'timezone',r.timezone,'horizon',case when r.horizon_starts_at is null then null else jsonb_build_object('startsAt',r.horizon_starts_at,'endsAt',r.horizon_ends_at) end,'source',r.source,'lastVerifiedAt',r.last_verified_at,'freshness',r.freshness,'validUntil',r.valid_until,'complete',r.complete,'availableWindows',r.available_windows,'readyPickupAreaId',r.ready_pickup_area_id)) into result from public.capacity_calendars r where r.id=p_id;
when 'maintenances' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'assetId',r.transport_asset_id,'blockedWindow',jsonb_build_object('startsAt',r.starts_at,'endsAt',r.ends_at),'kind',r.kind,'status',r.status,'source',r.source,'reason',r.reason)) into result from public.scheduled_maintenances r where r.id=p_id;
when 'repositioning-blocks' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'calendarId',r.capacity_calendar_id,'occupiedWindow',jsonb_build_object('startsAt',r.starts_at,'endsAt',r.ends_at),'origin',r.origin,'nextPickup',r.next_pickup,'estimatedTravelSeconds',r.estimated_travel_seconds,'status',r.status,'source',r.source,'reason',r.reason)) into result from public.repositioning_blocks r where r.id=p_id;
when 'asset-capabilities' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','serviceId',r.carrier_service_id,'assetId',r.transport_asset_id,'categoryId',r.cargo_category_id,'temperatureRange',case when r.temperature_min_c is null then null else jsonb_build_object('minCelsius',r.temperature_min_c,'maxCelsius',r.temperature_max_c) end,'certifications',r.certifications,'evidence',r.evidence,'verifiedAt',r.verified_at,'validUntil',r.valid_until,'active',r.active,'definitionId',r.definition_id)) into result from public.asset_cargo_capabilities r where r.id=p_id;
else raise exception 'INVALID_FLEET_KIND' using errcode='PT400';end case;return result;end;$$;

create or replace function private.command_v2_fleet(p_organization_id uuid,p_member_id uuid,p_kind text,p_carrier_id uuid,p_service_id uuid,p_id uuid,p_idempotency_key uuid,p_expected_version integer,p_value jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare t text; s json; h text; receipt private.v2_catalog_receipts%rowtype; current_version integer; saved_id uuid;
 sid uuid; parent_id uuid; cal_id uuid; w jsonb; other_w jsonb; start_at timestamptz; end_at timestamptz; result jsonb; previous jsonb;begin
 if p_service_id is not null or p_carrier_id is null then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
 perform private.authorize_v2_catalog(p_organization_id,p_member_id,'services',p_carrier_id,null,true,null);
 if p_idempotency_key is null or ((p_id is null) is distinct from (p_expected_version is null)) or p_expected_version<1 then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
 t:=private.fleet_target(p_kind);case p_kind
when 'capability-definitions' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"categoryId":{"type":"string","format":"uuid"},"requirements":{"type":"array","items":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"maxItems":100},"maxWeightKg":{"anyOf":[{"type":"number","exclusiveMinimum":0},{"type":"null"}]},"temperatureRange":{"anyOf":[{"type":"object","properties":{"minCelsius":{"type":"number"},"maxCelsius":{"type":"number"}},"required":["minCelsius","maxCelsius"],"additionalProperties":false},{"type":"null"}]},"certifications":{"type":"array","items":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"maxItems":100},"evidence":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"verifiedAt":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"validUntil":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"active":{"type":"boolean"}},"required":["schemaVersion","serviceId","categoryId","requirements","maxWeightKg","temperatureRange","certifications","evidence","verifiedAt","validUntil","active"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'assets' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"code":{"type":"string","pattern":"^[A-Z][A-Z0-9_]{0,99}$"},"mode":{"type":"string","enum":["ROAD","RAIL","SEA","AIR"]},"equipmentType":{"type":"string","enum":["BOX_TRUCK","REEFER_TRUCK","FLATBED","TANKER_TRUCK","TRACTOR_TRAILER","ISO_CONTAINER","RAIL_WAGON","AIR_ULD"]},"role":{"type":"string","enum":["LOAD_BEARING","AUXILIARY"]},"usefulCapacityKg":{"type":"number","minimum":0},"usableVolumeM3":{"anyOf":[{"type":"number","exclusiveMinimum":0},{"type":"null"}]},"operatingStatus":{"type":"string","enum":["AVAILABLE","IN_SERVICE","MAINTENANCE","OUT_OF_SERVICE"]},"homeDepotId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]},"provenance":{"type":"string","enum":["OWN","CONTRACTED","PARTNER"]},"partnerId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]},"evidence":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"roadVehicle":{"anyOf":[{"type":"object","properties":{"plate":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"registrationCode":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"registeredAt":{"anyOf":[{"type":"string","pattern":"^\\d{4}-\\d{2}-\\d{2}$"},{"type":"null"}]},"brand":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"model":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"variant":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"bodyType":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"usableDimensions":{"anyOf":[{"type":"object","properties":{"length":{"type":"number","exclusiveMinimum":0},"width":{"type":"number","exclusiveMinimum":0},"height":{"type":"number","exclusiveMinimum":0}},"required":["length","width","height"],"additionalProperties":false},{"type":"null"}]},"grossWeightLimitKg":{"anyOf":[{"type":"number","exclusiveMinimum":0},{"type":"null"}]},"odometerKm":{"anyOf":[{"type":"number","minimum":0},{"type":"null"}]},"conditionReason":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"axleConfig":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]}},"required":["plate","registrationCode","registeredAt","brand","model","variant","bodyType","usableDimensions","grossWeightLimitKg","odometerKm","conditionReason","axleConfig"],"additionalProperties":false},{"type":"null"}]}},"required":["schemaVersion","serviceId","code","mode","equipmentType","role","usefulCapacityKg","usableVolumeM3","operatingStatus","homeDepotId","provenance","partnerId","evidence","roadVehicle"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'capacity-pools' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"code":{"type":"string","pattern":"^[A-Z][A-Z0-9_]{0,99}$"},"mode":{"type":"string","enum":["ROAD","RAIL","SEA","AIR"]},"equipmentType":{"anyOf":[{"type":"string","enum":["BOX_TRUCK","REEFER_TRUCK","FLATBED","TANKER_TRUCK","TRACTOR_TRAILER","ISO_CONTAINER","RAIL_WAGON","AIR_ULD"]},{"type":"null"}]},"serviceWindow":{"type":"object","properties":{"startsAt":{"type":"string","format":"date-time"},"endsAt":{"type":"string","format":"date-time"}},"required":["startsAt","endsAt"],"additionalProperties":false},"declaredCapacity":{"type":"object","properties":{"weightKg":{"anyOf":[{"type":"number","exclusiveMinimum":0},{"type":"null"}]},"volumeM3":{"anyOf":[{"type":"number","exclusiveMinimum":0},{"type":"null"}]}},"required":["weightKg","volumeM3"],"additionalProperties":false},"provenance":{"type":"string","enum":["OWN","CONTRACTED","PARTNER"]},"partnerId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]},"evidence":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"supportedCargoCategoryIds":{"type":"array","items":{"type":"string","format":"uuid"},"maxItems":100},"active":{"type":"boolean"}},"required":["schemaVersion","serviceId","code","mode","equipmentType","serviceWindow","declaredCapacity","provenance","partnerId","evidence","supportedCargoCategoryIds","active"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'calendars' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"assetId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]},"capacityPoolId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]},"timezone":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"horizon":{"type":"object","properties":{"startsAt":{"type":"string","format":"date-time"},"endsAt":{"type":"string","format":"date-time"}},"required":["startsAt","endsAt"],"additionalProperties":false},"source":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"lastVerifiedAt":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"freshness":{"type":"string","enum":["VERIFIED","ESTIMATED","SIMULATED","UNKNOWN"]},"validUntil":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"complete":{"type":"boolean"},"availableWindows":{"type":"array","items":{"type":"object","properties":{"startsAt":{"type":"string","format":"date-time"},"endsAt":{"type":"string","format":"date-time"}},"required":["startsAt","endsAt"],"additionalProperties":false},"maxItems":100},"readyPickupAreaId":{"anyOf":[{"type":"string","format":"uuid"},{"type":"null"}]}},"required":["schemaVersion","serviceId","assetId","capacityPoolId","timezone","horizon","source","lastVerifiedAt","freshness","validUntil","complete","availableWindows","readyPickupAreaId"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'maintenances' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"assetId":{"type":"string","format":"uuid"},"blockedWindow":{"type":"object","properties":{"startsAt":{"type":"string","format":"date-time"},"endsAt":{"type":"string","format":"date-time"}},"required":["startsAt","endsAt"],"additionalProperties":false},"kind":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"status":{"type":"string","enum":["SCHEDULED","IN_PROGRESS","COMPLETED","CANCELLED"]},"source":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"reason":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"}},"required":["schemaVersion","serviceId","assetId","blockedWindow","kind","status","source","reason"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'repositioning-blocks' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"calendarId":{"type":"string","format":"uuid"},"occupiedWindow":{"type":"object","properties":{"startsAt":{"type":"string","format":"date-time"},"endsAt":{"type":"string","format":"date-time"}},"required":["startsAt","endsAt"],"additionalProperties":false},"origin":{"type":"object","properties":{"label":{"type":"string","minLength":1,"pattern":"\\S"},"countryCode":{"type":"string","pattern":"^[A-Z]{2}$"},"region":{"type":["string","null"]},"city":{"type":"string","minLength":1,"pattern":"\\S"},"lat":{"anyOf":[{"type":"number","minimum":-90,"maximum":90},{"type":"null"}]},"lng":{"anyOf":[{"type":"number","minimum":-180,"maximum":180},{"type":"null"}]}},"required":["label","countryCode","region","city","lat","lng"],"additionalProperties":false},"nextPickup":{"type":"object","properties":{"label":{"type":"string","minLength":1,"pattern":"\\S"},"countryCode":{"type":"string","pattern":"^[A-Z]{2}$"},"region":{"type":["string","null"]},"city":{"type":"string","minLength":1,"pattern":"\\S"},"lat":{"anyOf":[{"type":"number","minimum":-90,"maximum":90},{"type":"null"}]},"lng":{"anyOf":[{"type":"number","minimum":-180,"maximum":180},{"type":"null"}]}},"required":["label","countryCode","region","city","lat","lng"],"additionalProperties":false},"estimatedTravelSeconds":{"type":"integer","exclusiveMinimum":0},"status":{"type":"string","enum":["PLANNED","IN_PROGRESS","COMPLETED","CANCELLED"]},"source":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"reason":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"}},"required":["schemaVersion","serviceId","calendarId","occupiedWindow","origin","nextPickup","estimatedTravelSeconds","status","source","reason"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
when 'asset-capabilities' then s:='{"type":"object","properties":{"schemaVersion":{"type":"string","const":"2.0"},"serviceId":{"type":"string","format":"uuid"},"assetId":{"type":"string","format":"uuid"},"definitionId":{"type":"string","format":"uuid"},"categoryId":{"type":"string","format":"uuid"},"temperatureRange":{"anyOf":[{"type":"object","properties":{"minCelsius":{"type":"number"},"maxCelsius":{"type":"number"}},"required":["minCelsius","maxCelsius"],"additionalProperties":false},{"type":"null"}]},"certifications":{"type":"array","items":{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},"maxItems":100},"evidence":{"anyOf":[{"type":"string","minLength":1,"maxLength":500,"pattern":"\\S"},{"type":"null"}]},"verifiedAt":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"validUntil":{"anyOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"active":{"type":"boolean"}},"required":["schemaVersion","serviceId","assetId","definitionId","categoryId","temperatureRange","certifications","evidence","verifiedAt","validUntil","active"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}'::json;
end case;
 if not coalesce(extensions.jsonb_matches_schema(s,p_value),false) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
 sid:=(p_value->>'serviceId')::uuid;
 perform private.authorize_v2_catalog(p_organization_id,p_member_id,'areas',p_carrier_id,sid,true,null);
 -- Lock the service before examining references; all fleet commands for one service serialize.
 perform 1 from public.carrier_services where id=sid for update;
 h:=private.hash_v2_freight_payload(jsonb_build_object('kind',p_kind,'carrierId',p_carrier_id,'serviceId',null,'id',p_id,'expectedVersion',p_expected_version,'value',p_value));
 perform pg_advisory_xact_lock(hashtextextended(p_organization_id::text||':'||p_member_id::text||':'||p_idempotency_key::text,0));
 select * into receipt from private.v2_catalog_receipts where organization_id=p_organization_id and member_id=p_member_id and idempotency_key=p_idempotency_key;
 if found then if receipt.payload_hash<>h then raise exception 'IDEMPOTENCY_CONFLICT' using errcode='PT409';end if;
 return jsonb_build_object('record',receipt.result,'replay',true);end if;
 if p_id is not null then
  execute format('select version from public.%I where id=$1 and carrier_id=$2 and carrier_service_id=$3 for update',t) into current_version using p_id,p_carrier_id,sid;
  if current_version is null then raise exception 'CATALOG_NOT_FOUND' using errcode='PT404';end if;
  if current_version<>p_expected_version then raise exception 'STALE_DRAFT' using errcode='PT409';end if;
  previous:=private.fleet_record(p_kind,p_id)->'value';
 end if;
 if p_kind in ('assets','capacity-pools') then
  if (p_value->>'mode') is distinct from (select transport_mode from public.carrier_services where id=sid)
  or ((p_value->>'provenance'='PARTNER') is distinct from (p_value->>'partnerId' is not null)) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_value->>'partnerId' is not null and not exists(select 1 from public.fulfilment_partners where id=(p_value->>'partnerId')::uuid and carrier_id=p_carrier_id) then raise exception 'INVALID_PARTNER_SOURCE' using errcode='PT400';end if;
  if p_kind='assets' then
   if (p_value->>'mode'='ROAD') is distinct from (p_value->>'roadVehicle' is not null)
    or (p_value->>'role'='AUXILIARY' and ((p_value->>'usefulCapacityKg')::numeric<>0 or p_value->>'usableVolumeM3' is not null))
    or (p_value->>'role'='LOAD_BEARING' and (p_value->>'usefulCapacityKg')::numeric<=0) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  else
   if (p_value#>>'{serviceWindow,endsAt}')::timestamptz<=(p_value#>>'{serviceWindow,startsAt}')::timestamptz
    or exists(select 1 from jsonb_array_elements_text(p_value->'supportedCargoCategoryIds') id where not exists(select 1 from public.cargo_categories where cargo_categories.id=id::uuid and active))
    or jsonb_array_length(p_value->'supportedCargoCategoryIds')<>(select count(distinct id) from jsonb_array_elements_text(p_value->'supportedCargoCategoryIds') id) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  end if;
 end if;
 if p_kind='calendars' then
  if num_nonnulls(p_value->>'assetId',p_value->>'capacityPoolId')<>1 then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if not exists(select 1 from pg_timezone_names where name=p_value->>'timezone') then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  start_at:=(p_value#>>'{horizon,startsAt}')::timestamptz;end_at:=(p_value#>>'{horizon,endsAt}')::timestamptz;
  if end_at<=start_at or (p_value->>'lastVerifiedAt')::timestamptz>now()
   or (p_value->>'validUntil')::timestamptz<=(p_value->>'lastVerifiedAt')::timestamptz
   or (p_value->>'freshness'<>'UNKNOWN' and num_nonnulls(p_value->>'lastVerifiedAt',p_value->>'validUntil')<>2) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  for w in select value from jsonb_array_elements(p_value->'availableWindows') loop
   if (w->>'endsAt')::timestamptz<=(w->>'startsAt')::timestamptz or (w->>'startsAt')::timestamptz<start_at or (w->>'endsAt')::timestamptz>end_at then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  end loop;
  if exists(select 1 from jsonb_array_elements(p_value->'availableWindows') with ordinality a(w,i),jsonb_array_elements(p_value->'availableWindows') with ordinality b(w,i)
   where a.i<b.i and tstzrange((a.w->>'startsAt')::timestamptz,(a.w->>'endsAt')::timestamptz,'[)') && tstzrange((b.w->>'startsAt')::timestamptz,(b.w->>'endsAt')::timestamptz,'[)')) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_value->>'readyPickupAreaId' is not null and not exists(select 1 from public.service_areas where id=(p_value->>'readyPickupAreaId')::uuid and carrier_service_id=sid and area_role='PICKUP' and coverage='INCLUDE' and active) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_id is not null and (previous->>'assetId',previous->>'capacityPoolId') is distinct from (p_value->>'assetId',p_value->>'capacityPoolId') then raise exception 'IMMUTABLE_CAPACITY_SOURCE' using errcode='PT400';end if;
 end if;
 if p_kind in ('calendars','maintenances','asset-capabilities') and p_value->>'assetId' is not null then
  if not exists(select 1 from public.transport_assets where id=(p_value->>'assetId')::uuid and carrier_id=p_carrier_id and carrier_service_id=sid) then raise exception 'INVALID_FLEET_REFERENCE' using errcode='PT400';end if;
 end if;
 if p_kind='calendars' and p_value->>'capacityPoolId' is not null and not exists(select 1 from public.capacity_pools where id=(p_value->>'capacityPoolId')::uuid and carrier_id=p_carrier_id and carrier_service_id=sid) then raise exception 'INVALID_FLEET_REFERENCE' using errcode='PT400';end if;
 if p_kind in ('asset-capabilities','capability-definitions') then
  if not exists(select 1 from public.cargo_categories where id=(p_value->>'categoryId')::uuid and active)
   or (p_value#>>'{temperatureRange,maxCelsius}')::numeric<(p_value#>>'{temperatureRange,minCelsius}')::numeric
   or ((p_value#>>'{temperatureRange,minCelsius}') is null) is distinct from ((p_value#>>'{temperatureRange,maxCelsius}') is null)
   or (p_value->>'validUntil')::timestamptz<=(p_value->>'verifiedAt')::timestamptz
   or (p_value->>'verifiedAt')::timestamptz>now()
   or jsonb_array_length(p_value->'certifications')<>(select count(distinct v) from jsonb_array_elements_text(p_value->'certifications') v)
   then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_kind='capability-definitions' and jsonb_array_length(p_value->'requirements')<>(select count(distinct v) from jsonb_array_elements_text(p_value->'requirements') v) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_id is not null and (previous->>'assetId',previous->>'categoryId',previous->>'definitionId') is distinct from (p_value->>'assetId',p_value->>'categoryId',p_value->>'definitionId') then raise exception 'IMMUTABLE_CAPABILITY_SOURCE' using errcode='PT400';end if;
  if p_kind='asset-capabilities' and not exists(select 1 from public.cargo_capability_definitions d where d.id=(p_value->>'definitionId')::uuid and d.carrier_id=p_carrier_id and d.carrier_service_id=sid and d.active
   and d.cargo_category_id=(p_value->>'categoryId')::uuid and d.temperature_range is not distinct from nullif(p_value->'temperatureRange','null'::jsonb)
   and d.certifications=p_value->'certifications' and d.evidence is not distinct from p_value->>'evidence'
   and d.verified_at is not distinct from (p_value->>'verifiedAt')::timestamptz and d.valid_until is not distinct from (p_value->>'validUntil')::timestamptz)
   then raise exception 'INVALID_CAPABILITY_DEFINITION' using errcode='PT400';end if;
  if p_kind='capability-definitions' and p_id is not null and exists(select 1 from public.asset_cargo_capabilities a join public.capacity_calendars c on c.transport_asset_id=a.transport_asset_id
   join public.capacity_reservations r on r.capacity_calendar_id=c.id where a.definition_id=p_id and r.status in ('HELD','CONFIRMED') and r.ends_at>now()) then raise exception 'FLEET_COMMITMENT_CONFLICT' using errcode='PT409';end if;
 end if;
 if p_kind in ('maintenances','repositioning-blocks') then
  w:=p_value->case when p_kind='maintenances' then 'blockedWindow' else 'occupiedWindow' end;
  start_at:=(w->>'startsAt')::timestamptz;end_at:=(w->>'endsAt')::timestamptz;
  if end_at<=start_at or (p_kind='repositioning-blocks' and (p_value->>'estimatedTravelSeconds')::integer>extract(epoch from end_at-start_at)) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  if p_kind='repositioning-blocks' then
   if not exists(select 1 from public.capacity_calendars where id=(p_value->>'calendarId')::uuid and carrier_id=p_carrier_id and carrier_service_id=sid) then raise exception 'INVALID_FLEET_REFERENCE' using errcode='PT400';end if;
   if ((p_value#>>'{origin,lat}') is null) is distinct from ((p_value#>>'{origin,lng}') is null)
    or ((p_value#>>'{nextPickup,lat}') is null) is distinct from ((p_value#>>'{nextPickup,lng}') is null) then raise exception 'VALIDATION_ERROR' using errcode='PT400';end if;
  end if;
  if p_id is not null and p_value->>(case when p_kind='maintenances' then 'assetId' else 'calendarId' end)
   is distinct from previous->>(case when p_kind='maintenances' then 'assetId' else 'calendarId' end) then raise exception 'IMMUTABLE_BLOCK_SOURCE' using errcode='PT400';end if;
 end if;
 -- Serialize against reservations on the same calendar before changing availability.
 if p_kind='calendars' then cal_id:=p_id;
 elsif p_kind='repositioning-blocks' then cal_id:=(p_value->>'calendarId')::uuid;
 elsif p_kind in ('assets','capacity-pools') then
  select id into cal_id from public.capacity_calendars where (p_kind='assets' and transport_asset_id=p_id) or (p_kind='capacity-pools' and capacity_pool_id=p_id);
 elsif p_kind in ('maintenances','asset-capabilities') then select id into cal_id from public.capacity_calendars where transport_asset_id=(p_value->>'assetId')::uuid;
 end if;
 if cal_id is not null then
  perform 1 from public.capacity_calendars where id=cal_id for update;
  if exists(select 1 from public.capacity_reservations where capacity_calendar_id=cal_id and status in ('HELD','CONFIRMED') and ends_at>now()
    and (p_kind not in ('maintenances','repositioning-blocks') or (p_value->>'status' not in ('COMPLETED','CANCELLED') and tstzrange(starts_at,ends_at,'[)')&&tstzrange(start_at,end_at,'[)')))) then
   raise exception 'FLEET_COMMITMENT_CONFLICT' using errcode='PT409';end if;
 end if;
 case p_kind
when 'capability-definitions' then if p_id is null then insert into public.cargo_capability_definitions(carrier_service_id,cargo_category_id,requirements,max_weight_kg,temperature_range,certifications,evidence,verified_at,valid_until,active,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{categoryId}')::uuid,nullif(p_value#>'{requirements}','null'::jsonb),(p_value#>>'{maxWeightKg}')::numeric,nullif(p_value#>'{temperatureRange}','null'::jsonb),nullif(p_value#>'{certifications}','null'::jsonb),(p_value#>>'{evidence}')::text,(p_value#>>'{verifiedAt}')::timestamptz,(p_value#>>'{validUntil}')::timestamptz,(p_value#>>'{active}')::boolean,true,p_carrier_id) returning id into saved_id;
else update public.cargo_capability_definitions set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,cargo_category_id=(p_value#>>'{categoryId}')::uuid,requirements=nullif(p_value#>'{requirements}','null'::jsonb),max_weight_kg=(p_value#>>'{maxWeightKg}')::numeric,temperature_range=nullif(p_value#>'{temperatureRange}','null'::jsonb),certifications=nullif(p_value#>'{certifications}','null'::jsonb),evidence=(p_value#>>'{evidence}')::text,verified_at=(p_value#>>'{verifiedAt}')::timestamptz,valid_until=(p_value#>>'{validUntil}')::timestamptz,active=(p_value#>>'{active}')::boolean where id=p_id returning id into saved_id;end if;
when 'assets' then if p_id is null then insert into public.transport_assets(carrier_service_id,code,mode,equipment_code,asset_role,max_weight_kg,max_volume_m3,operating_status,active,home_depot_id,fulfilment_source,fulfilment_partner_id,evidence,plate,registration_code,registered_at,brand,model,variant,body_type,usable_dimensions,gross_weight_limit_kg,odometer_km,condition_reason,axle_config,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{code}')::text,(p_value#>>'{mode}')::text,(p_value#>>'{equipmentType}')::text,case when p_value->>'role'='LOAD_BEARING' then 'CARRIER' else 'ESCORT' end,case when p_value->>'role'='AUXILIARY' then null else (p_value#>>'{usefulCapacityKg}')::numeric end,(p_value#>>'{usableVolumeM3}')::numeric,(p_value#>>'{operatingStatus}')::text,(p_value->>'operatingStatus'='AVAILABLE'),(p_value#>>'{homeDepotId}')::uuid,(p_value#>>'{provenance}')::text,(p_value#>>'{partnerId}')::uuid,(p_value#>>'{evidence}')::text,(p_value#>>'{roadVehicle,plate}')::text,(p_value#>>'{roadVehicle,registrationCode}')::text,(p_value#>>'{roadVehicle,registeredAt}')::date,(p_value#>>'{roadVehicle,brand}')::text,(p_value#>>'{roadVehicle,model}')::text,(p_value#>>'{roadVehicle,variant}')::text,(p_value#>>'{roadVehicle,bodyType}')::text,nullif(p_value#>'{roadVehicle,usableDimensions}','null'::jsonb),(p_value#>>'{roadVehicle,grossWeightLimitKg}')::numeric,(p_value#>>'{roadVehicle,odometerKm}')::numeric,(p_value#>>'{roadVehicle,conditionReason}')::text,(p_value#>>'{roadVehicle,axleConfig}')::text,true,p_carrier_id) returning id into saved_id;
else update public.transport_assets set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,code=(p_value#>>'{code}')::text,mode=(p_value#>>'{mode}')::text,equipment_code=(p_value#>>'{equipmentType}')::text,asset_role=case when p_value->>'role'='LOAD_BEARING' then 'CARRIER' else 'ESCORT' end,max_weight_kg=case when p_value->>'role'='AUXILIARY' then null else (p_value#>>'{usefulCapacityKg}')::numeric end,max_volume_m3=(p_value#>>'{usableVolumeM3}')::numeric,operating_status=(p_value#>>'{operatingStatus}')::text,active=(p_value->>'operatingStatus'='AVAILABLE'),home_depot_id=(p_value#>>'{homeDepotId}')::uuid,fulfilment_source=(p_value#>>'{provenance}')::text,fulfilment_partner_id=(p_value#>>'{partnerId}')::uuid,evidence=(p_value#>>'{evidence}')::text,plate=(p_value#>>'{roadVehicle,plate}')::text,registration_code=(p_value#>>'{roadVehicle,registrationCode}')::text,registered_at=(p_value#>>'{roadVehicle,registeredAt}')::date,brand=(p_value#>>'{roadVehicle,brand}')::text,model=(p_value#>>'{roadVehicle,model}')::text,variant=(p_value#>>'{roadVehicle,variant}')::text,body_type=(p_value#>>'{roadVehicle,bodyType}')::text,usable_dimensions=nullif(p_value#>'{roadVehicle,usableDimensions}','null'::jsonb),gross_weight_limit_kg=(p_value#>>'{roadVehicle,grossWeightLimitKg}')::numeric,odometer_km=(p_value#>>'{roadVehicle,odometerKm}')::numeric,condition_reason=(p_value#>>'{roadVehicle,conditionReason}')::text,axle_config=(p_value#>>'{roadVehicle,axleConfig}')::text where id=p_id returning id into saved_id;end if;
when 'capacity-pools' then if p_id is null then insert into public.capacity_pools(carrier_service_id,code,mode,equipment_code,starts_at,ends_at,max_weight_kg,max_volume_m3,fulfilment_source,fulfilment_partner_id,evidence,supported_cargo_category_ids,active,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{code}')::text,(p_value#>>'{mode}')::text,(p_value#>>'{equipmentType}')::text,(p_value#>>'{serviceWindow,startsAt}')::timestamptz,(p_value#>>'{serviceWindow,endsAt}')::timestamptz,(p_value#>>'{declaredCapacity,weightKg}')::numeric,(p_value#>>'{declaredCapacity,volumeM3}')::numeric,(p_value#>>'{provenance}')::text,(p_value#>>'{partnerId}')::uuid,(p_value#>>'{evidence}')::text,array(select v::uuid from jsonb_array_elements_text(p_value->'supportedCargoCategoryIds') v),(p_value#>>'{active}')::boolean,true,p_carrier_id) returning id into saved_id;
else update public.capacity_pools set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,code=(p_value#>>'{code}')::text,mode=(p_value#>>'{mode}')::text,equipment_code=(p_value#>>'{equipmentType}')::text,starts_at=(p_value#>>'{serviceWindow,startsAt}')::timestamptz,ends_at=(p_value#>>'{serviceWindow,endsAt}')::timestamptz,max_weight_kg=(p_value#>>'{declaredCapacity,weightKg}')::numeric,max_volume_m3=(p_value#>>'{declaredCapacity,volumeM3}')::numeric,fulfilment_source=(p_value#>>'{provenance}')::text,fulfilment_partner_id=(p_value#>>'{partnerId}')::uuid,evidence=(p_value#>>'{evidence}')::text,supported_cargo_category_ids=array(select v::uuid from jsonb_array_elements_text(p_value->'supportedCargoCategoryIds') v),active=(p_value#>>'{active}')::boolean where id=p_id returning id into saved_id;end if;
when 'calendars' then if p_id is null then insert into public.capacity_calendars(carrier_service_id,transport_asset_id,capacity_pool_id,timezone,horizon_starts_at,horizon_ends_at,source_reference,source,observed_at,last_verified_at,provenance_status,freshness,valid_until,complete,available_windows,ready_pickup_area_id,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{assetId}')::uuid,(p_value#>>'{capacityPoolId}')::uuid,(p_value#>>'{timezone}')::text,(p_value#>>'{horizon,startsAt}')::timestamptz,(p_value#>>'{horizon,endsAt}')::timestamptz,(p_value#>>'{source}')::text,(p_value#>>'{source}')::text,(p_value#>>'{lastVerifiedAt}')::timestamptz,(p_value#>>'{lastVerifiedAt}')::timestamptz,(p_value#>>'{freshness}')::text,(p_value#>>'{freshness}')::text,(p_value#>>'{validUntil}')::timestamptz,(p_value#>>'{complete}')::boolean,nullif(p_value#>'{availableWindows}','null'::jsonb),(p_value#>>'{readyPickupAreaId}')::uuid,true,p_carrier_id) returning id into saved_id;
else update public.capacity_calendars set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,transport_asset_id=(p_value#>>'{assetId}')::uuid,capacity_pool_id=(p_value#>>'{capacityPoolId}')::uuid,timezone=(p_value#>>'{timezone}')::text,horizon_starts_at=(p_value#>>'{horizon,startsAt}')::timestamptz,horizon_ends_at=(p_value#>>'{horizon,endsAt}')::timestamptz,source_reference=(p_value#>>'{source}')::text,source=(p_value#>>'{source}')::text,observed_at=(p_value#>>'{lastVerifiedAt}')::timestamptz,last_verified_at=(p_value#>>'{lastVerifiedAt}')::timestamptz,provenance_status=(p_value#>>'{freshness}')::text,freshness=(p_value#>>'{freshness}')::text,valid_until=(p_value#>>'{validUntil}')::timestamptz,complete=(p_value#>>'{complete}')::boolean,available_windows=nullif(p_value#>'{availableWindows}','null'::jsonb),ready_pickup_area_id=(p_value#>>'{readyPickupAreaId}')::uuid where id=p_id returning id into saved_id;end if;
when 'maintenances' then if p_id is null then insert into public.scheduled_maintenances(carrier_service_id,transport_asset_id,starts_at,ends_at,kind,status,source,reason,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{assetId}')::uuid,(p_value#>>'{blockedWindow,startsAt}')::timestamptz,(p_value#>>'{blockedWindow,endsAt}')::timestamptz,(p_value#>>'{kind}')::text,(p_value#>>'{status}')::text,(p_value#>>'{source}')::text,(p_value#>>'{reason}')::text,true,p_carrier_id) returning id into saved_id;
else update public.scheduled_maintenances set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,transport_asset_id=(p_value#>>'{assetId}')::uuid,starts_at=(p_value#>>'{blockedWindow,startsAt}')::timestamptz,ends_at=(p_value#>>'{blockedWindow,endsAt}')::timestamptz,kind=(p_value#>>'{kind}')::text,status=(p_value#>>'{status}')::text,source=(p_value#>>'{source}')::text,reason=(p_value#>>'{reason}')::text where id=p_id returning id into saved_id;end if;
when 'repositioning-blocks' then if p_id is null then insert into public.repositioning_blocks(carrier_service_id,capacity_calendar_id,starts_at,ends_at,origin,next_pickup,estimated_travel_seconds,status,source,reason,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{calendarId}')::uuid,(p_value#>>'{occupiedWindow,startsAt}')::timestamptz,(p_value#>>'{occupiedWindow,endsAt}')::timestamptz,nullif(p_value#>'{origin}','null'::jsonb),nullif(p_value#>'{nextPickup}','null'::jsonb),(p_value#>>'{estimatedTravelSeconds}')::integer,(p_value#>>'{status}')::text,(p_value#>>'{source}')::text,(p_value#>>'{reason}')::text,true,p_carrier_id) returning id into saved_id;
else update public.repositioning_blocks set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,capacity_calendar_id=(p_value#>>'{calendarId}')::uuid,starts_at=(p_value#>>'{occupiedWindow,startsAt}')::timestamptz,ends_at=(p_value#>>'{occupiedWindow,endsAt}')::timestamptz,origin=nullif(p_value#>'{origin}','null'::jsonb),next_pickup=nullif(p_value#>'{nextPickup}','null'::jsonb),estimated_travel_seconds=(p_value#>>'{estimatedTravelSeconds}')::integer,status=(p_value#>>'{status}')::text,source=(p_value#>>'{source}')::text,reason=(p_value#>>'{reason}')::text where id=p_id returning id into saved_id;end if;
when 'asset-capabilities' then if p_id is null then insert into public.asset_cargo_capabilities(carrier_service_id,transport_asset_id,cargo_category_id,temperature_min_c,temperature_max_c,certifications,evidence,verified_at,valid_until,active,definition_id,fleet_managed,carrier_id) values((p_value#>>'{serviceId}')::uuid,(p_value#>>'{assetId}')::uuid,(p_value#>>'{categoryId}')::uuid,(p_value#>>'{temperatureRange,minCelsius}')::numeric,(p_value#>>'{temperatureRange,maxCelsius}')::numeric,nullif(p_value#>'{certifications}','null'::jsonb),(p_value#>>'{evidence}')::text,(p_value#>>'{verifiedAt}')::timestamptz,(p_value#>>'{validUntil}')::timestamptz,(p_value#>>'{active}')::boolean,(p_value#>>'{definitionId}')::uuid,true,p_carrier_id) returning id into saved_id;
else update public.asset_cargo_capabilities set fleet_managed=true,carrier_service_id=(p_value#>>'{serviceId}')::uuid,transport_asset_id=(p_value#>>'{assetId}')::uuid,cargo_category_id=(p_value#>>'{categoryId}')::uuid,temperature_min_c=(p_value#>>'{temperatureRange,minCelsius}')::numeric,temperature_max_c=(p_value#>>'{temperatureRange,maxCelsius}')::numeric,certifications=nullif(p_value#>'{certifications}','null'::jsonb),evidence=(p_value#>>'{evidence}')::text,verified_at=(p_value#>>'{verifiedAt}')::timestamptz,valid_until=(p_value#>>'{validUntil}')::timestamptz,active=(p_value#>>'{active}')::boolean,definition_id=(p_value#>>'{definitionId}')::uuid where id=p_id returning id into saved_id;end if;
end case;
 if p_kind='capability-definitions' then
  update public.asset_cargo_capabilities set temperature_min_c=(p_value#>>'{temperatureRange,minCelsius}')::numeric,temperature_max_c=(p_value#>>'{temperatureRange,maxCelsius}')::numeric,
   certifications=p_value->'certifications',evidence=p_value->>'evidence',verified_at=(p_value->>'verifiedAt')::timestamptz,valid_until=(p_value->>'validUntil')::timestamptz,active=(p_value->>'active')::boolean
   where definition_id=saved_id;
 end if;
 result:=private.fleet_record(p_kind,saved_id);
 insert into private.v2_catalog_receipts(organization_id,member_id,idempotency_key,payload_hash,result)
 values(p_organization_id,p_member_id,p_idempotency_key,h,result);
 return jsonb_build_object('record',result,'replay',false);end;$$;

create or replace function private.catalog_record(p_kind text,p_id uuid) returns jsonb language plpgsql set search_path='' as $$
declare result jsonb; begin case p_kind
when 'preferences' then select jsonb_build_object('id',r.id,'organizationId',r.organization_id,'carrierId',null,'serviceId',null,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','objective',r.objective,'maximumWaitMinutes',r.maximum_wait_minutes,'preferredMode',r.preferred_mode,'preferredEquipment',r.preferred_equipment,'usualBudget',r.usual_budget,'validUntil',r.valid_until)) into result from public.organization_preferences r where r.id=p_id;
when 'cargo-profiles' then select jsonb_build_object('id',r.id,'organizationId',r.organization_id,'carrierId',null,'serviceId',null,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','name',r.profile_name,'categoryId',r.cargo_category_id,'typicalUnits',r.typical_units,'requirements',r.requirements,'preferredEquipment',r.preferred_equipment,'active',r.active)) into result from public.organization_cargo_profiles r where r.id=p_id;
when 'cargo-categories' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',null,'serviceId',null,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('version',r.version::text,'schemaVersion','2.0','code',r.code,'name',r.name,'guidance',jsonb_build_object('recommendedEntryMethods',r.recommended_entry_methods,'intakeSpecificationSchema',r.intake_specification_schema,'suggestedRequirements',r.suggested_requirements,'recommendedVehicleClasses',r.recommended_vehicle_classes),'suggestedEquipment',r.suggested_equipment,'active',r.active)) into result from public.cargo_categories r where r.id=p_id;
when 'carriers' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.id,'serviceId',null,'verifiedContact',r.verified_contact,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','code',r.code,'commercialName',r.name,'legalName',r.legal_name,'businessIdType',r.business_identifier_type,'businessIdValue',r.business_identifier_value,'registeredCountry',r.registered_country,'providerType',r.provider_type,'status',r.status,'operationalPhone',r.operational_phone)) into result from public.carriers r where r.id=p_id;
when 'depots' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',null,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','code',r.code,'name',r.name,'location',jsonb_build_object('countryCode',r.country_code,'region',r.region_code,'city',r.city,'label',r.address_line,'lat',r.latitude,'lng',r.longitude),'active',r.active,'handling',r.handling)) into result from public.carrier_depots r where r.id=p_id;
when 'services' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',r.id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','mode',r.transport_mode,'serviceClass',r.service_type,'maxWeightKg',r.max_capacity_kg,'maxVolumeM3',r.max_volume_m3,'responseChannels',r.response_channels,'status',case when r.active then 'ACTIVE' else 'INACTIVE' end,'temperatureRange',case when r.temperature_min_c is null then null else jsonb_build_object('minCelsius',r.temperature_min_c,'maxCelsius',r.temperature_max_c) end,'requiredCertifications',r.required_certifications,'supportsHazardous',r.supports_hazardous,'supportsFragile',r.supports_fragile,'supportsOversized',r.supports_oversized,'admittedCargoTypes',coalesce((select jsonb_agg(c.cargo_category_id order by c.cargo_category_id) from public.carrier_service_cargo_categories c where c.carrier_service_id=r.id),'[]'::jsonb))) into result from public.carrier_services r where r.id=p_id;
when 'areas' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',(select carrier_id from public.carrier_services where id=r.carrier_service_id),'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','role',r.area_role,'inclusion',r.coverage,'geography',jsonb_build_object('granularity',r.granularity,'countryCode',r.country_code,'region',r.region_code,'city',r.city,'postalCode',r.postal_code,'geometry',r.geometry),'source',r.fulfilment_source,'partnerId',r.fulfilment_partner_id,'evidence',r.evidence_reference,'verifiedAt',r.verified_at,'validFrom',r.valid_from,'validUntil',r.valid_until,'active',r.active)) into result from public.service_areas r where r.id=p_id;
when 'lanes' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',(select carrier_id from public.carrier_services where id=r.carrier_service_id),'serviceId',r.carrier_service_id,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','pickupAreaId',r.pickup_area_id,'deliveryAreaId',r.delivery_area_id,'kind',r.lane_kind,'mode',r.transport_mode,'borderReviewRequired',r.cross_border_review_required,'evidence',r.evidence_reference,'verifiedAt',r.verified_at,'validFrom',r.valid_from,'validUntil',r.valid_until,'active',r.active,'plannedTransitMinutes',r.planned_transit_minutes,'transitProvenanceStatus',r.transit_provenance_status,'crossBorderProhibited',r.cross_border_prohibited,'crossBorderProhibitionReference',r.cross_border_prohibition_reference)) into result from public.service_lanes r where r.id=p_id;
when 'partners' then select jsonb_build_object('id',r.id,'organizationId',null,'carrierId',r.carrier_id,'serviceId',null,'version',r.version,'createdAt',r.created_at,'updatedAt',r.updated_at,'value',jsonb_build_object('schemaVersion','2.0','registeredName',r.registered_name,'partnerCarrierRef',r.partner_carrier_ref,'agreementValidFrom',r.agreement_valid_from,'agreementValidUntil',r.agreement_valid_until,'status',r.status,'coverageEvidence',r.coverage_evidence)) into result from public.fulfilment_partners r where r.id=p_id;
else raise exception 'INVALID_CATALOG_KIND' using errcode='PT400';end case;return result;end;$$;

create function private.workflow_planner_snapshot(d jsonb) returns jsonb
language sql immutable set search_path='' as $$
 select jsonb_build_object('algorithmVersion','PUBLISHED_ITINERARY_VALIDATOR_V1',
  'graphVersion',private.hash_v2_freight_payload(jsonb_build_object('corridorIds',d->'corridorIds',
   'policyId',d->'policyId','policyVersion',d->'policyVersion','legs',
   (select jsonb_agg(jsonb_build_object('corridorVersion',l->'corridorVersion',
    'originNodeVersion',l->'originNodeVersion','destinationNodeVersion',l->'destinationNodeVersion') order by ordinal)
    from jsonb_array_elements(d->'legs') with ordinality as legs(l,ordinal)))),
  'source',jsonb_build_object('kind','PUBLISHED_CORRIDORS','scope','SELECTED_ITINERARY_SNAPSHOT',
   'references',d->'corridorIds'));
$$;


create or replace function private.workflow_route(o uuid,qid uuid,ids jsonb,policy uuid,rid uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare q public.freight_requests;p public.route_planning_policies;c public.route_corridors;n1 public.logistics_nodes;n2 public.logistics_nodes;
 next_id uuid;prev uuid;seq integer:=0;leg uuid;x jsonb;origin jsonb;dest jsonb;reasons jsonb:='[]';distance numeric:=0;duration numeric:=0;known_distance boolean:=true;known_duration boolean:=true;
begin
 q:=private.workflow_request(o,qid);select * into p from public.route_planning_policies where id=policy and status='ACTIVE';
 if p.id is null then raise exception 'WORKFLOW_NOT_FOUND' using errcode='PT404';end if;
 insert into public.route_plans(id,organization_id,freight_request_id,status,policy_id,data) values(rid,o,qid,'unknown',policy,'{}');
 for next_id in select value::uuid from jsonb_array_elements_text(ids) loop
  seq:=seq+1;select * into c from public.route_corridors where id=next_id and status='ACTIVE';
  if c.id is null then raise exception 'WORKFLOW_NOT_FOUND' using errcode='PT404';end if;
  select * into n1 from public.logistics_nodes where id=c.origin_node_id;select * into n2 from public.logistics_nodes where id=c.destination_node_id;
  if seq>1 and prev<>c.origin_node_id then raise exception 'DISCONTINUOUS_ROUTE' using errcode='PT400';end if;
  if seq=1 then origin:=n1.data->'location';end if;dest:=n2.data->'location';prev:=c.destination_node_id;
  if not coalesce(q.v2_snapshot->'acceptedModes',jsonb_build_array(q.v2_snapshot->>'transportMode')) ? (c.data->>'mode') then raise exception 'ROUTE_MODE_MISMATCH' using errcode='PT400';end if;
  if n1.data#>>'{location,countryCode}'<>n2.data#>>'{location,countryCode}' and not exists(select 1 from jsonb_array_elements(c.data->'restrictions') req_rule where (req_rule->>'required')::boolean) then reasons:=reasons||'"BORDER_RULES_UNKNOWN"'::jsonb;end if;
  if c.data->>'mode'<>'ROAD' then reasons:=reasons||'"MODE_ADAPTER_UNVERIFIED"'::jsonb;end if;
  if n1.status<>'ACTIVE' or n2.status<>'ACTIVE' then raise exception 'NODE_INACTIVE' using errcode='PT400';end if;
  if not private.workflow_evidence(c.data->'source',q.pickup_window_start,q.delivery_window_end) or not private.workflow_evidence(n1.data->'source',q.pickup_window_start,q.delivery_window_end)
    or not private.workflow_evidence(n2.data->'source',q.pickup_window_start,q.delivery_window_end) then reasons:=reasons||'"ROUTE_SOURCE_UNKNOWN"'::jsonb;end if;
  for x in select value from jsonb_array_elements(c.data->'restrictions') union all select value from jsonb_array_elements(p.data->'constraints') loop
   if (x->>'required')::boolean and (not private.workflow_evidence(x->'evidence',q.pickup_window_start,q.delivery_window_end)
     or not exists(select 1 from jsonb_array_elements(coalesce(q.v2_snapshot#>'{cargoSpecification,availableDocuments}','[]')) doc where doc->>'code'=x->>'code'
       and doc->>'reference' is not null and (doc->>'issuedAt')::timestamptz<=now() and (doc->>'validUntil')::timestamptz>=q.delivery_window_end))
   then reasons:=reasons||jsonb_build_array('PERMIT_REQUIRED:'||(x->>'code'));end if;
  end loop;
  for x in select data from public.route_conditions where parent_id=c.id and status='ACTIVE'
    and (data->>'observedAt')::timestamptz<=now() and ((data->>'validUntil') is null or (data->>'validUntil')::timestamptz>now()) loop
   if x->>'kind'='CLOSURE' and x->>'confidence' in ('VERIFIED','SIMULATED') then reasons:=reasons||'"ROUTE_CLOSED"'::jsonb;
   else reasons:=reasons||jsonb_build_array('ROUTE_CONDITION:'||(x->>'kind'));end if;
  end loop;
  if c.data->>'estimatedDistanceKm' is null then known_distance:=false;else distance:=distance+(c.data->>'estimatedDistanceKm')::numeric;end if;
  if c.data->>'estimatedDurationSeconds' is null then known_duration:=false;else duration:=duration+(c.data->>'estimatedDurationSeconds')::numeric;end if;
  leg:=gen_random_uuid();insert into public.route_legs(id,route_plan_id,corridor_id,sequence,data) values(leg,rid,c.id,seq,
   jsonb_build_object('sequence',seq,'mode',c.data->'mode','origin',n1.data->'location','destination',n2.data->'location',
    'borderRequirements',c.data->'restrictions','estimatedDistanceKm',c.data->'estimatedDistanceKm','estimatedDurationSeconds',c.data->'estimatedDurationSeconds','waypoints',c.data->'waypoints','conditions',coalesce((select jsonb_agg(data) from public.route_conditions where parent_id=c.id and status='ACTIVE' and (data->>'observedAt')::timestamptz<=now() and ((data->>'validUntil') is null or (data->>'validUntil')::timestamptz>now())),'[]'::jsonb),'source',c.data->'source','corridorVersion',c.version,'originNodeVersion',n1.version,'destinationNodeVersion',n2.version));
  insert into public.route_waypoints(route_leg_id,sequence,data) select leg,ordinality,value from jsonb_array_elements(c.data->'waypoints') with ordinality;
 end loop;
 if lower(origin->>'city')<>lower(q.v2_snapshot#>>'{origin,city}') or origin->>'countryCode'<>q.v2_snapshot#>>'{origin,countryCode}'
 or lower(dest->>'city')<>lower(q.v2_snapshot#>>'{destination,city}') or dest->>'countryCode'<>q.v2_snapshot#>>'{destination,countryCode}' then raise exception 'ROUTE_REQUEST_ENDPOINT_MISMATCH' using errcode='PT400';end if;
 if (q.v2_snapshot#>>'{origin,lat}') is not null and origin->'lat' is distinct from q.v2_snapshot#>'{origin,lat}'
 or (q.v2_snapshot#>>'{origin,lng}') is not null and origin->'lng' is distinct from q.v2_snapshot#>'{origin,lng}'
 or (q.v2_snapshot#>>'{destination,lat}') is not null and dest->'lat' is distinct from q.v2_snapshot#>'{destination,lat}'
 or (q.v2_snapshot#>>'{destination,lng}') is not null and dest->'lng' is distinct from q.v2_snapshot#>'{destination,lng}' then reasons:=reasons||'"ENDPOINT_CONNECTOR_UNKNOWN"'::jsonb;end if;
 if known_duration and duration>extract(epoch from(q.delivery_window_end-q.pickup_window_start)) then reasons:=reasons||'"ROUTE_WINDOW_EXCEEDED"'::jsonb;end if;
 update public.route_plans set status=case when reasons ? 'ROUTE_CLOSED' or reasons ? 'ROUTE_WINDOW_EXCEEDED' then 'ineligible' when jsonb_array_length(reasons)>0 then 'unknown' else 'eligible' end,
 data=jsonb_build_object('origin',origin,'destination',dest,'corridorIds',ids,'policyId',policy,'policyVersion',p.version,'estimatedDistanceKm',case when known_distance then distance end,
  'estimatedDurationSeconds',case when known_duration then duration end,'geographicSource',jsonb_build_object('kind','PUBLISHED_CORRIDORS','references',ids),
  'confidence',case when jsonb_array_length(reasons)>0 then 'UNKNOWN' when exists(select 1 from public.route_corridors where id in(select value::uuid from jsonb_array_elements_text(ids)) and data#>>'{source,provenanceStatus}'='SIMULATED') or exists(select 1 from public.route_legs l join public.route_corridors cc on cc.id=l.corridor_id join public.logistics_nodes n on n.id in(cc.origin_node_id,cc.destination_node_id) where l.route_plan_id=rid and n.data#>>'{source,provenanceStatus}'='SIMULATED') then 'SIMULATED' else 'VERIFIED' end,'estimatedTolls',null,'borderCostEstimate',null,'reasons',reasons,
  'legs',(select jsonb_agg(data||jsonb_build_object('id',id,'corridorId',corridor_id) order by sequence) from public.route_legs where route_plan_id=rid)) where id=rid;
 update public.route_plans set data=data||jsonb_build_object('planner',private.workflow_planner_snapshot(data)) where id=rid;
 return private.workflow_record('routes',rid);end;$$;

create or replace function private.workflow_build_plan(o uuid,qid uuid,v jsonb,pid uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare q public.freight_requests;r public.route_plans;a jsonb;l jsonb;u jsonb;leg public.route_legs;svc public.carrier_services;res uuid;assign uuid;
 idx integer;qty integer;w numeric;vol numeric;state jsonb;begin
 q:=private.workflow_request(o,qid);select * into r from public.route_plans where id=(v->>'routeId')::uuid and organization_id=o and freight_request_id=qid;
 if r.id is null then raise exception 'WORKFLOW_NOT_FOUND' using errcode='PT404';end if;
 insert into public.transport_plan_candidates(id,organization_id,freight_request_id,route_plan_id,request_version,status,data) values(pid,o,qid,r.id,q.draft_version,'unknown','{}');
 for a in select value from jsonb_array_elements(v->'assignments') loop
  select * into leg from public.route_legs where route_plan_id=r.id and sequence=(a->>'legSequence')::integer;
  select * into svc from public.carrier_services where id=(a->>'serviceId')::uuid;
  if leg.id is null or svc.id is null then raise exception 'INVALID_PLAN_REFERENCE' using errcode='PT400';end if;
  if coalesce((select equipment_code from public.transport_assets where id=(a->>'assetId')::uuid),
    (select equipment_code from public.capacity_pools where id=(a->>'capacityPoolId')::uuid)) is null
  then raise exception 'RESOURCE_EQUIPMENT_REQUIRED' using errcode='PT409';end if;
  res:=gen_random_uuid();assign:=gen_random_uuid();
  insert into public.plan_resources(id,plan_id,carrier_id,carrier_service_id,calendar_id,asset_id,capacity_pool_id,combination_id,data) values(res,pid,svc.carrier_id,svc.id,(a->>'calendarId')::uuid,(a->>'assetId')::uuid,(a->>'capacityPoolId')::uuid,(a->>'combinationId')::uuid,
   jsonb_build_object('role',a->'role','equipment',coalesce((select equipment_code from public.transport_assets where id=(a->>'assetId')::uuid),(select equipment_code from public.capacity_pools where id=(a->>'capacityPoolId')::uuid)),'units',1,'window',a->'window','availability','UNKNOWN','applicableCapacity',null,'verificationSource',null));
  insert into public.plan_leg_assignments(id,plan_id,route_leg_id,resource_id,carrier_service_id,lane_id,sequence,starts_at,ends_at,data) values(assign,pid,leg.id,res,svc.id,(a->>'laneId')::uuid,leg.sequence,(a#>>'{window,startsAt}')::timestamptz,(a#>>'{window,endsAt}')::timestamptz,'{}');
  w:=0;vol:=0;
  for l in select value from jsonb_array_elements(a->'allocations') loop
   idx:=(l->>'unitIndex')::integer;qty:=(l->>'quantity')::integer;u:=q.v2_snapshot#>'{cargoSpecification,units}'->idx;
   if u is null or qty<1 or qty>(u->>'quantity')::integer then raise exception 'INVALID_LOAD_ALLOCATION' using errcode='PT400';end if;
   insert into public.load_allocations(assignment_id,unit_index,quantity,assigned_weight_kg,assigned_volume_m3,data) values(assign,idx,qty,qty*(u->>'weightPerUnitKg')::numeric,qty*(u->>'volumePerUnitM3')::numeric,
    jsonb_build_object('handlingRequirements',q.v2_snapshot#>'{cargoSpecification,requirements}','verification','UNKNOWN','indivisible',u->'indivisible','dimensionsCm',u->'dimensionsCm'));
   w:=w+qty*(u->>'weightPerUnitKg')::numeric;vol:=vol+qty*(u->>'volumePerUnitM3')::numeric;
  end loop;
  update public.plan_leg_assignments set data=jsonb_build_object('sequence',leg.sequence,'window',a->'window','responsibility',jsonb_build_object('carrierId',svc.carrier_id,'serviceId',svc.id),
   'coverage','UNKNOWN','availability','UNKNOWN','capacityNeeded',jsonb_build_object('weightKg',w,'volumeM3',vol),'evidence','[]'::jsonb) where id=assign;
 end loop;
 state:=private.workflow_evaluate_plan(pid);
 update public.plan_resources rr set data=rr.data||jsonb_build_object('availability',state->>'provenance','applicableCapacity',a.value->'applicableCapacity','verificationSource',a.value->'verificationSource')
  from jsonb_array_elements(state->'resourceAssessments') a where rr.plan_id=pid and rr.id=(a.value->>'resourceId')::uuid;
 update public.plan_leg_assignments set data=data||jsonb_build_object('coverage',state->>'provenance','availability',state->>'provenance') where plan_id=pid;
 update public.load_allocations set data=data||jsonb_build_object('verification',state->>'provenance') where assignment_id in(select id from public.plan_leg_assignments where plan_id=pid);
 update public.transport_plan_candidates set status=state->>'eligibility',data=state||jsonb_build_object('routeId',r.id,'requestVersion',q.draft_version,
  'proposedWindow',jsonb_build_object('startsAt',q.pickup_window_start,'endsAt',q.delivery_window_end),'coverage',state->>'provenance','availability',state->>'provenance',
  'assignments',(select jsonb_agg(aa.data||jsonb_build_object('id',aa.id,'resourceId',aa.resource_id,'serviceId',aa.carrier_service_id,'carrierId',rr.carrier_id,'resource',rr.data||jsonb_build_object('assetId',rr.asset_id,'poolId',rr.capacity_pool_id,'calendarId',rr.calendar_id,'combinationId',rr.combination_id),'allocations',coalesce((select jsonb_agg(ll.data||jsonb_build_object('unitIndex',ll.unit_index,'quantity',ll.quantity,'assignedWeightKg',ll.assigned_weight_kg,'assignedVolumeM3',ll.assigned_volume_m3)) from public.load_allocations ll where ll.assignment_id=aa.id),'[]'::jsonb))) from public.plan_leg_assignments aa join public.plan_resources rr on rr.id=aa.resource_id where aa.plan_id=pid)) where id=pid;
 return private.workflow_record('plans',pid);end;$$;

-- Backfill metadata solely from the original persisted itinerary snapshot.
update public.route_plans set data=data||jsonb_build_object('planner',private.workflow_planner_snapshot(data))
 where not data ? 'planner' and data ? 'legs';

revoke all on function private.workflow_planner_snapshot(jsonb) from public,anon,authenticated,service_role;

-- Preserve the authoritative receipt and project newly required metadata from
-- its original snapshot. Never substitute current route/catalog facts on replay.
alter function private.command_v2_workflow(uuid,uuid,text,jsonb,uuid,jsonb)
 rename to command_v2_workflow_before_cp1;
create function private.command_v2_workflow(p_organization_id uuid,p_member_id uuid,p_action text,p_context jsonb,p_key uuid,p_value jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb;record jsonb;begin
 result:=private.command_v2_workflow_before_cp1(p_organization_id,p_member_id,p_action,p_context,p_key,p_value);
 record:=result->'record';
 if record->>'kind'='routes' and not (record->'data') ? 'planner' then
  result:=jsonb_set(result,'{record,data,planner}',private.workflow_planner_snapshot(record->'data'));
 end if;
 return result;
end;$$;
revoke all on function private.command_v2_workflow(uuid,uuid,text,jsonb,uuid,jsonb),
 private.command_v2_workflow_before_cp1(uuid,uuid,text,jsonb,uuid,jsonb)
 from public,anon,authenticated,service_role;
