\set ON_ERROR_STOP on
\if :{?local_only}
\else
\set local_only 0
\endif
\if :local_only
\else
do $$
begin
    raise exception 'HAC44_LOCAL_ONLY';
end
$$;
\endif
\if :{?backup_confirmed}
\else
\set backup_confirmed 0
\endif
\if :backup_confirmed
\else
do $$
begin
    raise exception 'HAC44_BACKUP_REQUIRED: use the external-evidence QA runner';
end
$$;
\endif
begin;
select hac44_qa.capture_ids();
select 'HAC44_BEFORE:' || hac44_qa.counts()::text;
-- Incoming FK audit includes all implicit CASCADE edges and Auth user children.
select c.conrelid::regclass child,
c.confrelid::regclass parent,
c.conname,
c.confdeltype,
pg_get_constraintdef(
    c.oid
) from pg_constraint c where c.contype = 'f' and(
    c.confrelid = 'auth.users'::regclass or c.confrelid in(
        select to_regclass(
            relation
        ) from hac44_qa.ids where run_id = hac44_qa.current_run()
    )
) order by 1,
2,
3;
create temporary table hac44_remove(
    relation text,
    key jsonb,
    primary key(
        relation,
        key
    )
) on commit drop;
insert into hac44_remove select relation,
key from hac44_qa.ids where run_id = hac44_qa.current_run();
insert into hac44_remove select 'auth.users',
jsonb_build_object(
    'id',
    id
) from auth.users where id in(
    'd4410000-0000-4000-8000-000000000001',
    'd4410000-0000-4000-8000-000000000002',
    'd4410000-0000-4000-8000-000000000003'
);
-- No Auth identities/sessions are generated by the scenario. Never cascade them.
do $$
begin
    if exists(
        select 1 from auth.identities where user_id in(
            'd4410000-0000-4000-8000-000000000001',
            'd4410000-0000-4000-8000-000000000002',
            'd4410000-0000-4000-8000-000000000003'
        )
    ) or exists(
        select 1 from auth.sessions where user_id in(
            'd4410000-0000-4000-8000-000000000001',
            'd4410000-0000-4000-8000-000000000002',
            'd4410000-0000-4000-8000-000000000003'
        )
    ) then
        raise exception 'HAC44_AUTH_DEPENDENCIES_REQUIRE_EXPLICIT_BACKUP_IDS';
    end if;
end
$$;
-- Domain guards alone are suspended for exact QA-row teardown. FK/CHECK stay active.
do $$
declare
    t record;
begin
    for t in select s.* from hac44_qa.triggers s join pg_trigger p on p.tgrelid = to_regclass(
        s.relation
    ) and p.tgname = s.name where s.run_id = hac44_qa.current_run() and not p.tgisinternal and exists(
        select 1 from hac44_remove d where to_regclass(
            d.relation
        ) = to_regclass(
            s.relation
        )
    ) loop
        execute format(
            'alter table %s disable trigger %I',
            t.relation,
            t.name
        );
    end loop;
end
$$;
do $$
declare
    item record;
    fk record;
    joins text;
    childkey text;
    found boolean;
    blocked boolean;
    progress integer;
    n integer;
begin
    while exists(
        select 1 from hac44_remove
    ) loop
        progress := 0;
        for item in select * from hac44_remove order by relation,
        key loop
            blocked := false;
            for fk in select c.* from pg_constraint c where c.contype = 'f' and c.confrelid = to_regclass(
                item.relation
            ) loop
                select string_agg(
                    format(
                        'child.%I=parent.%I',
                        a.attname,
                        b.attname
                    ),
                    ' and '
                ) into joins from unnest(
                    fk.conkey,
                    fk.confkey
                ) k(
                    l,
                    r
                ) join pg_attribute a on a.attrelid = fk.conrelid and a.attnum = k.l join pg_attribute b on b.
                attrelid = fk.confrelid and b.attnum = k.r;
                -- A referenced parent waits for every actual child, so no CASCADE fires.
                execute format(
                    'select exists(select 1 from %s child join %s parent on %s where %s)',
                    fk.conrelid::regclass,
                    item.relation,
                    joins,
                    hac44_qa.where_key(
                        item.key,
                        'parent'
                    )
                ) into found;
                if found then
                    blocked := true;
                end if;
            end loop;
            if blocked then
                continue;
            end if;
            execute format(
                'delete from %s t where %s',
                item.relation,
                hac44_qa.where_key(
                    item.key
                )
            );
            get diagnostics n = row_count;
            if n > 1 then
                raise exception 'HAC44_NONUNIQUE_CLEANUP_KEY';
            end if;
            delete from hac44_remove where relation = item.relation and key = item.key;
            progress := progress + 1;
        end loop;
        if progress = 0 then
            raise exception 'HAC44_EXTERNAL_CHILD_OR_FK_CYCLE: exact IDs remain, preserve backup';
        end if;
    end loop;
end
$$;
do $$
declare
    t record;
    b record;
    actual jsonb;
    r uuid := hac44_qa.current_run();
begin
    for t in select s.* from hac44_qa.triggers s join pg_trigger p on p.tgrelid = to_regclass(
        s.relation
    ) and p.tgname = s.name where s.run_id = r and not p.tgisinternal loop
        execute format(
            'alter table %s %s trigger %I',
            t.relation,
            case t.enabled when 'O' then 'enable' when 'A' then 'enable always' when 'R' then 'enable replica' else
            'disable' end,
            t.name
        );
    end loop;
    for b in select * from hac44_qa.baseline where run_id = r loop
        execute format(
            'select coalesce(jsonb_agg(to_jsonb(t) order by hac44_qa.row_key(to_jsonb(t),%L::text[])),''[]'') from '
            '%s '
            't',
            b.pk,
            b.relation
        ) into actual;
        if actual <>(
            select coalesce(
                jsonb_agg(
                    x order by hac44_qa.row_key(
                        x,
                        b.pk
                    )
                ),
                '[]'
            ) from jsonb_array_elements(
                b.rows
            ) x
        ) then
            raise exception 'HAC44_BASELINE_CHANGED: %',
            b.relation;
        end if;
    end loop;
    if exists(
        select 1 from hac44_qa.triggers s left join pg_trigger pt on pt.tgrelid = to_regclass(
            s.relation
        ) and pt.tgname = s.name where s.run_id = r and(
            pt.oid is null or pt.tgenabled <> s.enabled
        )
    ) then
        raise exception 'HAC44_TRIGGER_STATE_CHANGED';
    end if;
    if exists(
        select 1 from jsonb_each(
            hac44_qa.counts()
        ) x where x.value <> '0'::jsonb
    ) then
        raise exception 'HAC44_CLEANUP_NOT_ZERO';
    end if;
    update hac44_qa.runs set finished_at = now() where id = r;
end
$$;
select 'HAC44_AFTER:' || hac44_qa.counts()::text;
commit;
